# Generated by Django 4.2.1 on 2023-09-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_newuserinfo_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuserinfo',
            old_name='bio',
            new_name='userBio',
        ),
        migrations.RenameField(
            model_name='newuserinfo',
            old_name='user',
            new_name='userId',
        ),
    ]
