# Generated by Django 4.2.1 on 2023-09-23 20:15

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LinkPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpage',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='yourPage', editable=False, populate_from='title', unique=True),
        ),
    ]
