# Generated by Django 4.2.1 on 2023-09-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LinkPage', '0002_linkpage_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkpage',
            name='slug',
        ),
    ]
