# Generated by Django 4.2.1 on 2023-09-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkPage', '0005_remove_link_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
