# Generated by Django 4.2.1 on 2023-09-23 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LinkPage', '0007_alter_linkpage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpage',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
