# Generated by Django 4.2.1 on 2023-09-24 09:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LinkPage', '0008_alter_linkpage_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkpage',
            name='url',
        ),
        migrations.AddField(
            model_name='linkpage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
